# Configurazione Server (Spring Boot girerà qui)
spring.application.name=eclettici-backend
server.port=8082
server.address=0.0.0.0

# Configurazione sicurezza Token JWT
app.jwt.secret=LaTuaChiaveSegretissimaEAltamenteSicuraPerIlProgettoEclettici2026!
app.jwt.expiration-ms=1800000

# Connessione al Database (Porta 5433 mappata da Docker per questo progetto)
spring.datasource.url=jdbc:postgresql://192.168.1.30:5433/eclettici_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione JPA/Hibernate
## spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true